name: SonarCloud Scan and PR

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
        SONAR_ORGANIZATION_KEY: ${{ secrets.SONAR_ORGANIZATION_KEY }}

    
    - name: Analyze SonarCloud results
      id: analyze-results
      run: |
        # Add a script to analyze the scan results and output the required fixes.
        echo "::set-output name=fixes::$(./gptscripts/analyze_results.sh)"

    - name: Implement fixes using GPT-4 API
      if: steps.analyze-results.outputs.fixes != ''
      run: |
        # Add a script to use GPT-4 API to implement the suggested fixes.
        ./gptscripts/implement_fixes.sh "${{ steps.analyze-results.outputs.fixes }}"

    - name: Commit changes and create PR
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: "Fix SonarCloud findings"
        title: "Fix SonarCloud findings"
        body: "This PR addresses the SonarCloud findings."